POST http://localhost:3000/login
Content-Type: application/json

{
    "name": "Facundo",
    "password": "123456"
}

###

GET http://localhost:3000/greetings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmFjdeyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiRmFjdW5kbyIsImlhdCI6MTYyODA0MDM4OX0.LropQRZYav4N4KDcaxZKmj1IV9HOs9dFXBCyYN56_jkW5kbyIsImlhdCI6MTYyODA0MDI0OH0.QckMM00f7w5XRgawKZcB3FhehBeo0VQIapOCwvuuRGc

